# Generated by Django 2.0.9 on 2019-04-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='life_motto',
            field=models.TextField(default='Even the tallest and most formidable of towers was once just a pile of bricks'),
            preserve_default=False,
        ),
    ]
